import React, { useRef } from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { MdPictureAsPdf, MdClose } from 'react-icons/md';
import { saveAs } from 'file-saver';
import Swal from 'sweetalert2';

/**
 * ExamPDFExport — Generates Merit List PDF and Individual Result Slips
 * from an existing exam's data directly (no extra API calls).
 */
const ExamPDFExport = ({ exam, results, onClose }) => {

    const fetchLogo = async () => {
        try {
            const logoPath = '/logo.png';
            // Use a controller to timeout the fetch after 2 seconds
            const controller = new AbortController();
            const timeoutId = setTimeout(() => controller.abort(), 2000);

            const response = await fetch(logoPath, { signal: controller.signal });
            clearTimeout(timeoutId);

            if (!response.ok) return null;
            const blob = await response.blob();
            return new Promise((resolve) => {
                const reader = new FileReader();
                reader.onloadend = () => resolve(reader.result);
                reader.onerror = () => resolve(null);
                reader.readAsDataURL(blob);
            });
        } catch (error) {
            console.error("PDF Logo Fetch Error (Skipping logo):", error);
            return null;
        }
    };

    // Use results directly as they are already ranked from Exam.jsx
    const ranked = (results || []).map(r => ({
        ...r,
        mcqMarks: Number(r.mcqMarks) || 0,
        writenMarks: Number(r.writenMarks) || 0,
        total: Number(r.total) || (Number(r.mcqMarks) || 0) + (Number(r.writenMarks) || 0)
    }));

    const eMcqTotal = Number(exam.mcqTotal) || 0;
    const eWrittenTotal = Number(exam.writenTotal) || 0;
    const eGrandTotal = eMcqTotal + eWrittenTotal;

    const highest = ranked.length ? ranked[0].total : 0;
    const avg = ranked.length ? (ranked.reduce((a, r) => a + r.total, 0) / ranked.length).toFixed(1) : 0;

    // â”€â”€â”€ MERIT LIST PDF â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    const handleMeritListPDF = async () => {
        const doc = new jsPDF('portrait', 'mm', 'a4');
        const logo = await fetchLogo();
        const pageW = doc.internal.pageSize.width;

        // Header
        if (logo) {
            try {
                doc.addImage(logo, 'PNG', 14, 8, 20, 20);
            } catch (e) {
                console.error("Error adding image to PDF:", e);
                // Fallback: Just draw a circle or text if image fails
                doc.setDrawColor(14, 165, 233);
                doc.circle(24, 18, 10, 'S');
            }
        }
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(14, 165, 233); // Match brand color
        doc.text('Sohag Physics', pageW / 2, 16, { align: 'center' });
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.text('Merit List', pageW / 2, 23, { align: 'center' });
        doc.setFontSize(9);
        doc.text(exam.title || 'Exam Results', pageW / 2, 29, { align: 'center' });
        doc.text(`Date: ${exam.date || ''}   |   Batch: ${exam.batch || ''}   |   Total Participants: ${ranked.length}`, pageW / 2, 35, { align: 'center' });

        // Table
        const headers = [['Merit', 'Roll', 'Name', `MCQ (${eMcqTotal})`, `Written (${eWrittenTotal})`, `Total (${eGrandTotal})`]];
        const rows = ranked.map(r => [
            r.merit,
            r.id,
            r.name,
            r.mcqMarks,
            r.writenMarks,
            r.total
        ]);

        autoTable(doc, {
            head: headers,
            body: rows,
            startY: 40,
            theme: 'striped',
            headStyles: {
                fillColor: [14, 165, 233],
                textColor: [255, 255, 255],
                fontStyle: 'bold',
                halign: 'center',
                fontSize: 9,
            },
            bodyStyles: { halign: 'center', fontSize: 8.5 },
            columnStyles: {
                0: { cellWidth: 15 },
                1: { cellWidth: 18 },
                2: { cellWidth: 60, halign: 'left' },
                3: { cellWidth: 25 },
                4: { cellWidth: 25 },
                5: { cellWidth: 25 },
            },
            alternateRowStyles: { fillColor: [240, 249, 255] },
            margin: { left: 14, right: 14 },
            didDrawPage: (data) => {
                // Footer
                const pageCount = doc.internal.getNumberOfPages();
                doc.setFontSize(7);
                doc.setTextColor(150);
                doc.text(`Page ${data.pageNumber} of ${pageCount}`, pageW / 2, doc.internal.pageSize.height - 8, { align: 'center' });
                doc.text('Generated by Sohag Physics Management System', pageW / 2, doc.internal.pageSize.height - 4, { align: 'center' });
                doc.setTextColor(0);
            }
        });

        // Top 3 highlight box at top right
        doc.setPage(1);
        const top3 = ranked.slice(0, 3);
        doc.setFillColor(240, 249, 255);
        doc.roundedRect(pageW - 60, 8, 46, top3.length * 7 + 10, 3, 3, 'F');
        doc.setFontSize(7.5);
        doc.setFont('helvetica', 'bold');
        doc.text('ðŸ† Top Performers', pageW - 37, 14, { align: 'center' });
        doc.setFont('helvetica', 'normal');
        top3.forEach((r, i) => {
            const medals = ['ðŸ¥‡', 'ðŸ¥ˆ', 'ðŸ¥‰'];
            const nickName = r.name ? r.name.split(' ')[0] : 'Student';
            doc.text(`${medals[i]} ${nickName} — ${r.total}`, pageW - 57, 20 + i * 7);
        });

        Swal.fire({
            title: 'Generating Merit List...',
            html: 'Please wait while we prepare your PDF',
            allowOutsideClick: false,
            didOpen: () => Swal.showLoading()
        });

        try {
            const pdfBlob = doc.output('blob');
            saveAs(pdfBlob, `Merit_List_${exam.title.replace(/\s+/g, '_')}.pdf`);
            Swal.close();
            Swal.fire({ icon: 'success', title: 'PDF Ready!', timer: 1500, showConfirmButton: false });
        } catch (err) {
            console.error("MERIT LIST PDF ERROR:", err);
            Swal.close();
            Swal.fire({ icon: 'error', title: 'Generation Failed', text: String(err.message) + ' (See Console)' });
            alert(err.stack);
        }
    };

    // â”€â”€â”€ RESULT SLIPS PDF â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    const handleResultSlipsPDF = async () => {
        const doc = new jsPDF('portrait', 'mm', 'a4');
        const logo = await fetchLogo();
        const pageW = doc.internal.pageSize.width;
        const pageH = doc.internal.pageSize.height;

        // 2 slips per page
        const slipH = (pageH - 30) / 2;

        const drawSlip = (result, yStart, isLast) => {
            const x = 14;
            const w = pageW - 28;

            // Slip border
            doc.setDrawColor(14, 165, 233);
            doc.setLineWidth(0.4);
            doc.roundedRect(x, yStart + 2, w, slipH - 4, 4, 4);

            // Header strip
            doc.setFillColor(14, 165, 233);
            doc.roundedRect(x, yStart + 2, w, 14, 4, 4, 'F');
            doc.rect(x, yStart + 8, w, 8, 'F'); // square bottom corners

            if (logo) doc.addImage(logo, 'PNG', x + 3, yStart + 4, 10, 10);
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            doc.text('Sohag Physics', pageW / 2, yStart + 10, { align: 'center' });
            doc.setFontSize(7.5);
            doc.setFont('helvetica', 'normal');
            doc.text('Result Slip', pageW / 2, yStart + 14.5, { align: 'center' });

            // Student info
            doc.setTextColor(0, 0, 0);
            const infoY = yStart + 22;
            doc.setFontSize(9);
            doc.setFont('helvetica', 'bold');
            doc.text(result.name, x + 5, infoY);
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(8);
            doc.text(`Roll: ${result.id}`, x + 5, infoY + 6);
            doc.text(`Exam: ${exam.title}`, x + 5, infoY + 12);
            doc.text(`Date: ${exam.date}`, x + 5, infoY + 18);

            // Merit badge (top right of slip)
            doc.setFillColor(255, 237, 100);
            doc.roundedRect(x + w - 35, yStart + 18, 30, 20, 3, 3, 'F');
            doc.setFontSize(7);
            doc.setFont('helvetica', 'bold');
            doc.text('MERIT POSITION', x + w - 20, yStart + 24, { align: 'center' });
            doc.setFontSize(18);
            doc.setTextColor(14, 100, 200);
            doc.text(`#${result.merit}`, x + w - 20, yStart + 35, { align: 'center' });
            doc.setTextColor(0);

            // Score table
            autoTable(doc, {
                head: [['Component', 'Obtained', 'Total', 'Percentage']],
                body: [
                    ['MCQ', result.mcqMarks, eMcqTotal, eMcqTotal ? `${((result.mcqMarks / eMcqTotal) * 100).toFixed(1)}%` : 'N/A'],
                    ['Written', result.writenMarks, eWrittenTotal, eWrittenTotal ? `${((result.writenMarks / eWrittenTotal) * 100).toFixed(1)}%` : 'N/A'],
                    ['Total', result.total, eGrandTotal, eGrandTotal ? `${((result.total / eGrandTotal) * 100).toFixed(1)}%` : '0%'],
                ],
                startY: infoY + 22,
                theme: 'grid',
                headStyles: {
                    fillColor: [240, 249, 255],
                    textColor: [14, 100, 200],
                    fontStyle: 'bold',
                    fontSize: 8,
                    halign: 'center',
                },
                bodyStyles: { fontSize: 8, halign: 'center' },
                columnStyles: {
                    0: { halign: 'left', cellWidth: 28 },
                    1: { cellWidth: 24 },
                    2: { cellWidth: 24 },
                    3: { cellWidth: 30 },
                },
                margin: { left: x + 3, right: x + w - 90 },
                tableWidth: w - 40,
            });

            // Highest mark
            const highestTotal = ranked[0]?.total || 0;
            const finalY = doc.lastAutoTable?.finalY ? doc.lastAutoTable.finalY + 3 : infoY + 45;
            doc.setFontSize(7.5);
            doc.setTextColor(100);
            doc.text(`Highest in Class: ${highestTotal} / ${eGrandTotal}   |   Class Avg: ${avg}`, x + 5, finalY);
            doc.setTextColor(0);

            // Dotted divider between slips
            if (!isLast) {
                doc.setDrawColor(180);
                doc.setLineDash([2, 2]);
                doc.line(x, yStart + slipH, x + w, yStart + slipH);
                doc.setLineDash([]);
                doc.setDrawColor(0);
            }
        };

        ranked.forEach((result, i) => {
            if (i > 0 && i % 2 === 0) doc.addPage();
            const position = i % 2;
            const yStart = 10 + position * slipH;
            drawSlip(result, yStart, position === 1 || i === ranked.length - 1);
        });

        Swal.fire({
            title: 'Generating Result Slips...',
            html: `Preparing ${ranked.length} slips`,
            allowOutsideClick: false,
            didOpen: () => Swal.showLoading()
        });

        try {
            const pdfBlob = doc.output('blob');
            saveAs(pdfBlob, `Result_Slips_${exam.title.replace(/\s+/g, '_')}.pdf`);
            Swal.close();
            Swal.fire({ icon: 'success', title: 'PDF Ready!', timer: 1500, showConfirmButton: false });
        } catch (err) {
            console.error("RESULT SLIP PDF ERROR:", err);
            Swal.close();
            Swal.fire({ icon: 'error', title: 'Generation Failed', text: String(err.message) + ' (See Console)' });
            alert(err.stack);
        }
    };



    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/60 backdrop-blur-sm">
            <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-8 border-t-4 border-sky-500">
                {/* Header */}
                <div className="flex items-start justify-between mb-6">
                    <div>
                        <h2 className="text-xl font-black text-slate-800">PDF Export</h2>
                        <p className="text-slate-500 text-sm mt-1">{exam.title}</p>
                        <p className="text-slate-400 text-xs">{exam.date}</p>
                    </div>
                    <button onClick={onClose} className="p-2 text-slate-400 hover:text-red-500 rounded-xl transition-colors">
                        <MdClose size={22} />
                    </button>
                </div>

                {/* Stats preview */}
                <div className="grid grid-cols-3 gap-3 mb-6 p-4 bg-slate-50 rounded-xl">
                    <div className="text-center">
                        <p className="text-2xl font-black text-sky-600">{ranked.length}</p>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Students</p>
                    </div>
                    <div className="text-center border-x border-slate-200">
                        <p className="text-2xl font-black text-emerald-600">{highest}</p>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Highest</p>
                    </div>
                    <div className="text-center">
                        <p className="text-2xl font-black text-indigo-600">{avg}</p>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Average</p>
                    </div>
                </div>

                {/* Export options */}
                <div className="space-y-3">
                    <button
                        onClick={handleMeritListPDF}
                        className="w-full flex items-center gap-4 p-4 bg-sky-50 hover:bg-sky-100 border border-sky-200 rounded-xl transition-all group"
                    >
                        <div className="w-12 h-12 bg-sky-600 rounded-xl flex items-center justify-center text-white shadow-md group-hover:scale-110 transition-transform">
                            <MdPictureAsPdf size={24} />
                        </div>
                        <div className="text-left">
                            <p className="font-black text-slate-800 text-sm">Merit List PDF</p>
                            <p className="text-slate-500 text-xs">Full ranked list with scores • A4 Portrait</p>
                        </div>
                    </button>

                    <button
                        onClick={handleResultSlipsPDF}
                        className="w-full flex items-center gap-4 p-4 bg-indigo-50 hover:bg-indigo-100 border border-indigo-200 rounded-xl transition-all group"
                    >
                        <div className="w-12 h-12 bg-indigo-600 rounded-xl flex items-center justify-center text-white shadow-md group-hover:scale-110 transition-transform">
                            <MdPictureAsPdf size={24} />
                        </div>
                        <div className="text-left">
                            <p className="font-black text-slate-800 text-sm">Individual Result Slips</p>
                            <p className="text-slate-500 text-xs">2 slips per page • Merit, score & breakdown</p>
                        </div>
                    </button>
                </div>

                <p className="text-center text-[10px] text-slate-300 mt-5 font-medium">
                    PDF generation uses existing exam data • No extra server calls
                </p>
            </div>
        </div>
    );
};

export default ExamPDFExport;
