import React, { useRef } from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { MdPictureAsPdf, MdClose } from 'react-icons/md';
import { saveAs } from 'file-saver';
import Swal from 'sweetalert2';

/**
 * ExamPDFExport — Generates Merit List PDF, Full A4 Report Cards, and Individual Result Slips
 * from an existing exam's data directly (no extra API calls).
 */
const ExamPDFExport = ({ exam, results, onClose }) => {

    const fetchLogo = async () => {
        try {
            const logoPath = '/logo.png';
            const controller = new AbortController();
            const timeoutId = setTimeout(() => controller.abort(), 2000);

            const response = await fetch(logoPath, { signal: controller.signal });
            clearTimeout(timeoutId);

            if (!response.ok) return null;
            const blob = await response.blob();
            return new Promise((resolve) => {
                const reader = new FileReader();
                reader.onloadend = () => resolve(reader.result);
                reader.onerror = () => resolve(null);
                reader.readAsDataURL(blob);
            });
        } catch (error) {
            console.error("PDF Logo Fetch Error (Skipping logo):", error);
            return null;
        }
    };

    const ranked = (results || []).map(r => ({
        ...r,
        mcqMarks: Number(r.mcqMarks) || 0,
        writenMarks: Number(r.writenMarks) || 0,
        total: Number(r.total) || (Number(r.mcqMarks) || 0) + (Number(r.writenMarks) || 0)
    }));

    const eMcqTotal = Number(exam.mcqTotal) || 0;
    const eWrittenTotal = Number(exam.writenTotal) || 0;
    const eGrandTotal = eMcqTotal + eWrittenTotal;

    const highest = ranked.length ? ranked[0].total : 0;
    const avg = ranked.length ? (ranked.reduce((a, r) => a + r.total, 0) / ranked.length).toFixed(1) : 0;

    // ─── MERIT LIST PDF ──────────────────────────────────────────────────────────
    const handleMeritListPDF = async () => {
        const doc = new jsPDF('portrait', 'mm', 'a4');
        const logo = await fetchLogo();
        const pageW = doc.internal.pageSize.width;

        if (logo) {
            try { doc.addImage(logo, 'PNG', 14, 8, 20, 20); } catch (e) {
                doc.setDrawColor(14, 165, 233);
                doc.circle(24, 18, 10, 'S');
            }
        }
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(14, 165, 233);
        doc.text('Sohag Physics', pageW / 2, 16, { align: 'center' });
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.text('Merit List', pageW / 2, 23, { align: 'center' });
        doc.setFontSize(9);
        doc.text(exam.title || 'Exam Results', pageW / 2, 29, { align: 'center' });
        doc.text(`Date: ${exam.date || ''}   |   Batch: ${exam.batch || ''}   |   Total Participants: ${ranked.length}`, pageW / 2, 35, { align: 'center' });

        const headers = [['Merit', 'Roll', 'Name', `MCQ (${eMcqTotal})`, `Written (${eWrittenTotal})`, `Total (${eGrandTotal})`]];
        const rows = ranked.map(r => [r.merit, r.id, r.name, r.mcqMarks, r.writenMarks, r.total]);

        autoTable(doc, {
            head: headers,
            body: rows,
            startY: 40,
            theme: 'striped',
            headStyles: { fillColor: [14, 165, 233], textColor: [255, 255, 255], fontStyle: 'bold', halign: 'center', fontSize: 9 },
            bodyStyles: { halign: 'center', fontSize: 8.5 },
            columnStyles: { 0: { cellWidth: 15 }, 1: { cellWidth: 18 }, 2: { cellWidth: 60, halign: 'left' }, 3: { cellWidth: 25 }, 4: { cellWidth: 25 }, 5: { cellWidth: 25 } },
            margin: { left: 14, right: 14 },
            didDrawPage: (data) => {
                const pageCount = doc.internal.getNumberOfPages();
                doc.setFontSize(7);
                doc.setTextColor(150);
                doc.text(`Page ${data.pageNumber} of ${pageCount}`, pageW / 2, doc.internal.pageSize.height - 8, { align: 'center' });
                doc.text('Generated by Sohag Physics Management System', pageW / 2, doc.internal.pageSize.height - 4, { align: 'center' });
            }
        });

        const top3 = ranked.slice(0, 3);
        doc.setFillColor(240, 249, 255);
        doc.roundedRect(pageW - 60, 8, 46, top3.length * 7 + 10, 3, 3, 'F');
        doc.setFontSize(7.5);
        doc.setFont('helvetica', 'bold');
        doc.text('🏆 Top Performers', pageW - 37, 14, { align: 'center' });
        doc.setFont('helvetica', 'normal');
        top3.forEach((r, i) => {
            const medals = ['🥇', '🥈', '🥉'];
            const nickName = r.name ? r.name.split(' ')[0] : 'Student';
            doc.text(`${medals[i]} ${nickName} — ${r.total}`, pageW - 57, 20 + i * 7);
        });

        Swal.fire({ title: 'Generating Merit List...', didOpen: () => Swal.showLoading() });
        try {
            saveAs(doc.output('blob'), `Merit_List_${exam.title.replace(/\s+/g, '_')}.pdf`);
            Swal.close();
            Swal.fire({ icon: 'success', title: 'PDF Ready!', timer: 1000, showConfirmButton: false });
        } catch (err) { Swal.close(); }
    };

    // ─── FULL REPORT CARDS (A4) ──────────────────────────────────────────────────
    const handleReportCardsPDF = async () => {
        const doc = new jsPDF('portrait', 'mm', 'a4');
        const logo = await fetchLogo();
        const pageW = doc.internal.pageSize.width;
        const pageH = doc.internal.pageSize.height;

        const drawReportCard = (result) => {
            doc.setDrawColor(14, 165, 233);
            doc.setLineWidth(1); doc.rect(5, 5, pageW - 10, pageH - 10);
            doc.setLineWidth(0.2); doc.rect(7, 7, pageW - 14, pageH - 14);

            if (logo) doc.addImage(logo, 'PNG', pageW / 2 - 15, 15, 30, 30);
            doc.setFontSize(24); doc.setFont('helvetica', 'bold');
            doc.setTextColor(14, 165, 233); doc.text('SOHAG PHYSICS', pageW / 2, 55, { align: 'center' });
            doc.setFontSize(10); doc.setTextColor(100); doc.setFont('helvetica', 'normal');
            doc.text('ACADEMIC EXCELLENCE & GUIDANCE', pageW / 2, 62, { align: 'center' });
            doc.setDrawColor(230); doc.line(20, 68, pageW - 20, 68);
            doc.setFontSize(14); doc.setTextColor(0); doc.setFont('helvetica', 'bold');
            doc.text('ACADEMIC REPORT CARD', pageW / 2, 78, { align: 'center' });

            doc.setFillColor(248, 250, 252); doc.roundedRect(20, 85, pageW - 40, 45, 3, 3, 'F');
            doc.setFontSize(11); doc.setTextColor(14, 100, 200); doc.text('STUDENT INFORMATION', 25, 93);
            doc.setTextColor(0); doc.setFont('helvetica', 'normal');
            doc.text(`Name:`, 25, 103); doc.setFont('helvetica', 'bold'); doc.text(result.name || 'N/A', 60, 103);
            doc.setFont('helvetica', 'normal'); doc.text(`Roll ID:`, 25, 111); doc.setFont('helvetica', 'bold'); doc.text(result.id || 'N/A', 60, 111);
            doc.setFont('helvetica', 'normal'); doc.text(`Batch:`, 25, 119); doc.setFont('helvetica', 'bold'); doc.text(exam.batch || 'N/A', 60, 119);
            doc.setFont('helvetica', 'normal'); doc.text(`Exam Name:`, 110, 103); doc.setFont('helvetica', 'bold'); doc.text(exam.title || 'N/A', 140, 103);
            doc.setFont('helvetica', 'normal'); doc.text(`Exam Date:`, 110, 111); doc.setFont('helvetica', 'bold'); doc.text(exam.date || 'N/A', 140, 111);

            autoTable(doc, {
                head: [['ASSESSMENT COMPONENT', 'FULL MARKS', 'OBTAINED MARKS', 'PERCENTAGE']],
                body: [
                    ['Multi-Choice Question (MCQ)', eMcqTotal, result.mcqMarks, eMcqTotal ? `${((result.mcqMarks / eMcqTotal) * 100).toFixed(1)}%` : '0%'],
                    ['Written Assessment', eWrittenTotal, result.writenMarks, eWrittenTotal ? `${((result.writenMarks / eWrittenTotal) * 100).toFixed(1)}%` : '0%'],
                    ['Grand Total Output', eGrandTotal, result.total, eGrandTotal ? `${((result.total / eGrandTotal) * 100).toFixed(1)}%` : '0%'],
                ],
                startY: 140, theme: 'grid',
                headStyles: { fillColor: [14, 165, 233], textColor: 255, halign: 'center', cellPadding: 4 },
                bodyStyles: { halign: 'center', cellPadding: 4, fontSize: 10 },
                columnStyles: { 0: { halign: 'left', cellWidth: 70 } },
                margin: { left: 20, right: 20 }
            });

            const finalY = doc.lastAutoTable.finalY + 15;
            doc.setFillColor(255, 243, 232); doc.roundedRect(20, finalY, 80, 40, 4, 4, 'F');
            doc.setFontSize(10); doc.setTextColor(150, 80, 0); doc.text('MERIT POSITION', 60, finalY + 10, { align: 'center' });
            doc.setFontSize(28); doc.text(`#${result.merit}`, 60, finalY + 30, { align: 'center' });
            doc.setFillColor(236, 253, 245); doc.roundedRect(110, finalY, 80, 40, 4, 4, 'F');
            doc.setFontSize(10); doc.setTextColor(5, 150, 105); doc.text('CLASS PERFORMANCE', 150, finalY + 10, { align: 'center' });
            doc.setFontSize(10); doc.text(`Class Highest: ${highest} / ${eGrandTotal}`, 115, finalY + 22);
            doc.text(`Class Average: ${avg} / ${eGrandTotal}`, 115, finalY + 32);

            const sigY = pageH - 40; doc.setTextColor(0); doc.setFontSize(9);
            doc.line(30, sigY, 70, sigY); doc.text("Guardian's Signature", 50, sigY + 5, { align: 'center' });
            doc.line(140, sigY, 180, sigY); doc.text("Authorized Signature", 160, sigY + 5, { align: 'center' });
            doc.setFontSize(8); doc.setTextColor(150);
            doc.text(`This is a computer-generated report. No signature required for validation.`, pageW / 2, pageH - 15, { align: 'center' });
            doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageW / 2, pageH - 10, { align: 'center' });
        };

        ranked.forEach((res, i) => { if (i > 0) doc.addPage(); drawReportCard(res); });
        Swal.fire({ title: 'Generating Report Cards...', didOpen: () => Swal.showLoading() });
        saveAs(doc.output('blob'), `Report_Cards_${exam.title.replace(/\s+/g, '_')}.pdf`);
        Swal.close();
    };

    // ─── RESULT SLIPS ────────────────────────────────────────────────────────────
    const handleResultSlipsPDF = async () => {
        const doc = new jsPDF('portrait', 'mm', 'a4');
        const logo = await fetchLogo();
        const pageW = doc.internal.pageSize.width;
        const pageH = doc.internal.pageSize.height;
        const slipH = (pageH - 30) / 2;

        const drawSlip = (result, yStart, isLast) => {
            const x = 14, w = pageW - 28;
            doc.setDrawColor(14, 165, 233); doc.setLineWidth(0.4); doc.roundedRect(x, yStart + 2, w, slipH - 4, 4, 4);
            doc.setFillColor(14, 165, 233); doc.roundedRect(x, yStart + 2, w, 14, 4, 4, 'F'); doc.rect(x, yStart + 8, w, 8, 'F');
            if (logo) doc.addImage(logo, 'PNG', x + 3, yStart + 4, 10, 10);
            doc.setTextColor(255); doc.setFontSize(12); doc.setFont('helvetica', 'bold');
            doc.text('Sohag Physics', pageW / 2, yStart + 10, { align: 'center' });
            doc.setFontSize(7.5); doc.setFont('helvetica', 'normal'); doc.text('Result Slip', pageW / 2, yStart + 14.5, { align: 'center' });

            doc.setTextColor(0); doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.text(result.name, x + 5, yStart + 22);
            doc.setFont('helvetica', 'normal'); doc.setFontSize(8);
            doc.text(`Roll: ${result.id}`, x + 5, yStart + 28); doc.text(`Exam: ${exam.title}`, x + 5, yStart + 34); doc.text(`Date: ${exam.date}`, x + 5, yStart + 40);

            doc.setFillColor(255, 237, 100); doc.roundedRect(x + w - 35, yStart + 18, 30, 20, 3, 3, 'F');
            doc.setFontSize(7); doc.setFont('helvetica', 'bold'); doc.text('MERIT POSITION', x + w - 20, yStart + 24, { align: 'center' });
            doc.setFontSize(18); doc.setTextColor(14, 100, 200); doc.text(`#${result.merit}`, x + w - 20, yStart + 35, { align: 'center' });

            autoTable(doc, {
                head: [['Component', 'Obtained', 'Total', '%']],
                body: [
                    ['MCQ', result.mcqMarks, eMcqTotal, eMcqTotal ? `${((result.mcqMarks / eMcqTotal) * 100).toFixed(1)}%` : '0%'],
                    ['Written', result.writenMarks, eWrittenTotal, eWrittenTotal ? `${((result.writenMarks / eWrittenTotal) * 100).toFixed(1)}%` : '0%'],
                    ['Total', result.total, eGrandTotal, eGrandTotal ? `${((result.total / eGrandTotal) * 100).toFixed(1)}%` : '0%'],
                ],
                startY: yStart + 44, theme: 'grid',
                headStyles: { fillColor: [240, 249, 255], textColor: [14, 100, 200], fontSize: 8, halign: 'center' },
                bodyStyles: { fontSize: 8, halign: 'center' },
                columnStyles: { 0: { halign: 'left', cellWidth: 28 } },
                margin: { left: x + 3, right: x + w - 90 }, tableWidth: w - 40,
            });

            if (!isLast) { doc.setDrawColor(180); doc.setLineDash([2, 2]); doc.line(x, yStart + slipH, x + w, yStart + slipH); doc.setLineDash([]); }
        };

        ranked.forEach((res, i) => { if (i % 2 === 0 && i > 0) doc.addPage(); drawSlip(res, 10 + (i % 2) * slipH, (i % 2) === 1 || i === ranked.length - 1); });
        Swal.fire({ title: 'Generating Slips...', didOpen: () => Swal.showLoading() });
        saveAs(doc.output('blob'), `Slips_${exam.title.replace(/\s+/g, '_')}.pdf`);
        Swal.close();
    };

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/60 backdrop-blur-sm">
            <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-8 border-t-4 border-sky-500">
                <div className="flex items-start justify-between mb-6">
                    <div>
                        <h2 className="text-xl font-black text-slate-800">PDF Export Hub</h2>
                        <p className="text-slate-500 text-sm mt-1">{exam.title}</p>
                    </div>
                    <button onClick={onClose} className="p-2 text-slate-400 hover:text-red-500 rounded-xl transition-colors"><MdClose size={22} /></button>
                </div>

                <div className="space-y-3">
                    <button onClick={handleMeritListPDF} className="w-full flex items-center gap-4 p-4 bg-sky-50 hover:bg-sky-100 border border-sky-200 rounded-xl transition-all group">
                        <div className="w-12 h-12 bg-sky-600 rounded-xl flex items-center justify-center text-white shadow-md group-hover:scale-110 transition-transform"><MdPictureAsPdf size={24} /></div>
                        <div className="text-left"><p className="font-black text-slate-800 text-sm">Merit List PDF</p><p className="text-slate-500 text-xs">Full ranked list • A4 Portrait</p></div>
                    </button>

                    <button onClick={handleReportCardsPDF} className="w-full flex items-center gap-4 p-4 bg-emerald-50 hover:bg-emerald-100 border border-emerald-200 rounded-xl transition-all group">
                        <div className="w-12 h-12 bg-emerald-600 rounded-xl flex items-center justify-center text-white shadow-md group-hover:scale-110 transition-transform"><MdPictureAsPdf size={24} /></div>
                        <div className="text-left"><p className="font-black text-slate-800 text-sm">Formal Report Cards</p><p className="text-slate-500 text-xs">Individual A4 page per student</p></div>
                    </button>

                    <button onClick={handleResultSlipsPDF} className="w-full flex items-center gap-4 p-4 bg-indigo-50 hover:bg-indigo-100 border border-indigo-200 rounded-xl transition-all group">
                        <div className="w-12 h-12 bg-indigo-600 rounded-xl flex items-center justify-center text-white shadow-md group-hover:scale-110 transition-transform"><MdPictureAsPdf size={24} /></div>
                        <div className="text-left"><p className="font-black text-slate-800 text-sm">Result Slips</p><p className="text-slate-500 text-xs">2 slips per page • Compact</p></div>
                    </button>
                </div>
            </div>
        </div>
    );
};

export default ExamPDFExport;
